#!/bin/bash

read -rp "VM NAME: " VM
PipeName="${VM//[^A-Za-z0-9._-]/_}"

pwsh.exe -Command "
Start-Process -FilePath sudo -ArgumentList @(\"pwsh.exe\", \"-Command\", @\"
Set-VMComPort -VMName '$VM' -Number 1 -Path '\\\\.\\pipe\\$PipeName'
Start-VM '$VM'
# convey.exe \\\\.\\pipe\\$PipeName
\"@) -Wait
"

pwsh.exe -Command '
$pipe = [System.IO.Pipes.NamedPipeClientStream]::new(".", "'$PipeName'", [System.IO.Pipes.PipeDirection]::In)

while ($true) {
    try {
        $pipe.Connect(1000)
        break
    }
    catch {
        Start-Sleep -Milliseconds 200
    }
}

$sr = [System.IO.StreamReader]::new($pipe)

while ($sr.Peek() -eq -1) {
    Start-Sleep -Milliseconds 100
}

while ($true) {
    $n = $sr.Peek()
    if ($n -ge 0) {
        [Console]::Write([char]$sr.Read())
    } else {
        Start-Sleep -Milliseconds 50
    }
}
'
