#!/bin/bash

pwsh.exe -Command '
$VM = Read-Host -Prompt "VM NAME"

sudo pwsh.exe -Command "
    Set-VMComPort -VMName `"$VM`" -Number 1 `"\\.\pipe\$VM`" | Out-Null
    Start-VM `"$VM`" | Out-Null
"

$pipe = New-Object System.IO.Pipes.NamedPipeClientStream(".", "$VM", [System.IO.Pipes.PipeDirection]::In)
$pipe.Connect()

$sr = New-Object System.IO.StreamReader($pipe)

while ($true) {
    $n = $sr.Peek()
    if ($n -ge 0) {
        $ch = [char]$sr.Read()
        if ($ch -ne "`r") {
            [Console]::Write($ch)
        }
    }
    else {
        Start-Sleep -Milliseconds 100
    }
    if ($sr.EndOfStream) {
        break
    }
}
'
